### PR TITLE
CM - Refactoring tasks due to JBPM-5452 and standalone showcase integration

### PR DESCRIPTION
**Pull request by romartin**
Hi Mike,

Well the merge was quite easy, as expected, so good :) 

This PR depends on [this one](https://github.com/manstis/droolsjbpm-build-bootstrap/pull/1).

I finally checked out a new branch from yours, rebased to master, merged conflicts and refactored a few things and that's it! Hope that you can checkout and merge my work, and no issues appear.

Some updates:
* Removed unused control implentations for CM except the drag one, which I'm considering it mandatory for Full sessions right now... so have to review this, dont worry
* Added read-only session support and some cleans for the session stuff
* Split CM modules for project extensions
* Added CM into the standalone showcase. Would recommend you to use it, builds and runs faster. You can add as well a CM bpmn2 file in the WEF-INF/diagrams, if you need it to be added by default on the VFS once running the standalone showcase, so you can open it.
* The preview works much better now! Just using a different canvas color... hehe :/

So well, hope this works as expected, any issues lemme know!! 

BTW I have seen you started working on the graph & command side! good. feel free to change whatever you think! what you think about this stuff? I know it's not easy but dont see how to do it easier.. :( so any suggestions/critisicm wil be appreciated!! xD

Best regards!
Roger

### CODE REVIEW

**Comment by romartin** [comment]
@manstis I had to rebase so this PR says that cannot be merged.. please just checkout my commits and force your push with yout author etc, 
Hope you can do it and no issues! I have tested CM in both showcases and works fine! lemme know whatever! Thanks!

**Comment by romartin** [comment]
oh no, as while I was doing the rebase work eder added a new commit, it appears on top of your work!!! :( now what? Eder's commit is really small but not sure how to handle this commit.. :/

**Comment by romartin** [comment]
arghh sorry I think I'm getting confused with this info... looking at [my source branch](https://github.com/romartin/kie-wb-common/commits/JBPM-5452-CM) for this PR it's all good!

**Comment by manstis** [comment]
@romartin Arrrrrrrrrrrrgggggggggggggghh! This is proving a complete feck-fest to merge!!

**Comment by manstis** [comment]
@romartin Finally merged into my fork and [PR](https://github.com/droolsjbpm/kie-wb-common/pull/654) submitted for ```droolsjbpm/master@kie-wb-common```. Closing this PR as it was merged (and squashed) with https://github.com/manstis/kie-wb-common/commit/3bb68278a8e990cc73c4399c3e7f7885ef679c74

**Pull request closed without merging**
